name: CICD workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build tcp server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: make

  format:
    name: Code format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Run format check
      run: make format-check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make test
