name: CICD workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build tcp server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: make

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: aminya/setup-cpp@v1
      with:
        clangformat: true

    - name: Run format check
      run: make format-check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make test
